language: ruby

git:
  depth: false

branches:
  only:
    - master
    - beta
    - stable

env:
  global:
    - TRAVIS_NODE_VERSION="10"
    - DISCOURSE_HOSTNAME=www.example.com
    - RUBY_GLOBAL_METHOD_CACHE_SIZE=131072
    - RAILS_MASTER=0
    - CI_NODE_TOTAL=2
  matrix:
    - "QUNIT_RUN=1 RUN_LINT=0 RUN_PLUGINS=0"
    - "QUNIT_RUN=0 RUN_LINT=1 RUN_PLUGINS=0"
    - "QUNIT_RUN=0 RUN_LINT=0 RUN_PLUGINS=0 CI_NODE_INDEX=0"
    - "QUNIT_RUN=0 RUN_LINT=0 RUN_PLUGINS=0 CI_NODE_INDEX=1"
    - "QUNIT_RUN=0 RUN_LINT=0 RUN_PLUGINS=1"
addons:
  chrome: stable
  postgresql: 9.6
  apt:
    update: true
    packages:
      - gifsicle
      - jpegoptim
      - optipng
      - jhead

matrix:
  fast_finish: true

rvm:
  - 2.5.3

services:
  - redis-server

sudo: required
dist: trusty

cache:
  apt: true
  yarn: true
  directories:
    - vendor/bundle

before_install:
  - wget -qO- https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/install-pngquant | sudo sh
  - nvm install node
  - node --version
  - gem install bundler -v 1.17.3
  - bash -c "if [ '$RUN_PLUGINS' == '1' ]; then git clone --depth=1 https://github.com/discourse/discourse-backup-uploads-to-s3.git plugins/discourse-backup-uploads-to-s3; fi"
  - bash -c "if [ '$RUN_PLUGINS' == '1' ]; then git clone --depth=1 https://github.com/discourse/discourse-spoiler-alert.git plugins/discourse-spoiler-alert; fi"
  - bash -c "if [ '$RUN_PLUGINS' == '1' ]; then git clone --depth=1 https://github.com/discourse/discourse-cakeday.git plugins/discourse-cakeday; fi"
  - bash -c "if [ '$RUN_PLUGINS' == '1' ]; then git clone --depth=1 https://github.com/discourse/discourse-canned-replies.git plugins/discourse-canned-replies; fi"
  - bash -c "if [ '$RUN_PLUGINS' == '1' ]; then git clone --depth=1 https://github.com/discourse/discourse-chat-integration.git plugins/discourse-chat-integration; fi"
  - bash -c "if [ '$RUN_PLUGINS' == '1' ]; then git clone --depth=1 https://github.com/discourse/discourse-assign.git plugins/discourse-assign; fi"
  - bash -c "if [ '$RUN_PLUGINS' == '1' ]; then git clone --depth=1 https://github.com/discourse/discourse-patreon.git plugins/discourse-patreon; fi"
  - bash -c "if [ '$RUN_PLUGINS' == '1' ]; then git clone --depth=1 https://github.com/discourse/discourse-staff-notes.git plugins/discourse-staff-notes; fi"
  - bash -c "if [ '$RUN_PLUGINS' == '1' ]; then git clone --depth=1 https://github.com/discourse/discourse-group-tracker; fi"
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - bash -c "if [ '$RAILS_MASTER' == '1' ]; then bundle update --retry=3 --jobs=3 arel rails seed-fu; fi"
  - bash -c "if [ '$RAILS_MASTER' == '0' ] && [ '$RUN_LINT' != '1' ]; then bundle install --without development --deployment --retry=3 --jobs=3; fi"
  - bash -c "if [ '$QUNIT_RUN' == '1' ] || [ '$RUN_LINT' == '1' ]; then yarn install; fi"
  - bash -c "if [ '$RUN_PLUGINS' == '1' ] || [ '$RUN_PLUGINS' == '1' ]; then LOAD_PLUGINS=1 bundle exec rake db:create db:migrate; fi"

script:
  - |
    bash -c "
      if [ '$RUN_LINT' == '1' ]; then
        bundle exec rubocop --parallel && \
        bundle exec danger && \
        yarn eslint --ext .es6 app/assets/javascripts && \
        yarn eslint --ext .es6 test/javascripts && \
        yarn eslint --ext .es6 plugins/**/assets/javascripts && \
        yarn eslint --ext .es6 plugins/**/test/javascripts && \
        yarn eslint app/assets/javascripts test/javascripts
      else
        if [ '$QUNIT_RUN' == '1' ]; then
          bundle exec rake qunit:test['500000'] && \
          bundle exec rake qunit:test['500000','/wizard/qunit'] && \
          bundle exec rake plugin:qunit
        else
          if [ '$RUN_PLUGINS' == '1' ]; then
            bundle exec rake plugin:spec
          else
            bundle exec rake knapsack:rspec
          fi
        fi
      fi
    "
